version = 0.1

[default.deploy.parameters]
stack_name = "iamigos-dental"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
image_repositories = []
s3_prefix = "iamigos-dental"